remote_theme : minimal-mistakes@master
plugins :
- jekyll-remote-theme
title : Berry Recognizer
description : An image classification API that classifies 10 different berry types found around the globe.
author:
 name : Md Zahidul Islam